version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - echo "Current directory: $(pwd)"
      - echo "Listing files in lib:"
      - ls -la
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - echo "Current directory after returning to root: $(pwd)"
      - echo "Listing files in root:"
      - ls -la
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating MoniMonitor_Bot Function..."
      - aws lambda update-function-code --function-name MoniMonitor_Bot --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
